### ISSUE TITLE
[BUG] Tabbing to Auto-Complete Values

### ISSUE THREAD

**Issue by InValidFire** [bridge-core/bridge.#101]
**Summary**

**To Reproduce**
1. Go to a file where autocompletion works with values. (ie blocks.json)
2. Start typing a value you want to add, do not complete it
3. Using arrow keys, select an option from the suggested list
4. Press TAB to auto complete
5. Observe results

**Observed behavior**
You will see only the partially typed result get added. After some testing, it seems it *does* add both values, however the intended value is overwritten by the unintended value.

(ctrl+z corrects the unintended value, hinting that this is being overwritten)

**Expected behavior**
It will add the autocompleted value to the file, completely ignoring the partially typed result.

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

PREPARING TO AUTO COMPLETE
![image](https://user-images.githubusercontent.com/32578904/67966484-52aca800-fbda-11e9-87f6-60a3daaf72bb.png)

AFTER TAB COMPLETION
![image](https://user-images.githubusercontent.com/32578904/67966530-6821d200-fbda-11e9-8bc3-424580d4011e.png)

AFTER CTRL+Z
![image](https://user-images.githubusercontent.com/32578904/67966557-7839b180-fbda-11e9-853b-4f3febc9d1cf.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - App Version: 0.13.17

**Additional context**
Just like #100, this happens only with the keyboard shortcuts. Clicking with the mouse produces the intended result.

**Comment by MSpaceDev** [comment]
Current workaround: Use the RETURN key instead =)

**Comment by solvedDev** [comment]
I am keeping an eye on the related issues of the UI framework I am using. There's already a pull request open for this specific input issue
