### ISSUE TITLE
[BUG] Bridge saves file improperly on Linux

### ISSUE THREAD

**Issue by CollinScripter** [bridge-core/bridge.#129]
**Summary**
After creating a project, saving a file results in the file being saved in an incorrect file path.

**To Reproduce**
1. Launch the Bridge AppImage on Linux
2. Create a new pack
3. Create and/or modify a file
4. Save the file
5. Observe resulting file in folder where bridge was launched

**Observed behavior**
When saving a modified file, the file is saved in the current directory with the name of the file path where it should have been saved, with inverted slashes.
**Expected behavior**
When saving a modified file, the file is saved in /home/username/.local/share/mcpelauncher/games/com.mojang/development_behavior_packs/

**Screenshots / File Attachments**
![Bridge File Save](https://user-images.githubusercontent.com/5771065/71316053-b4013280-2437-11ea-97cb-cff99ab2b054.gif)

**Platform:**
 - OS: Kubuntu 19.10
 - App Version: 0.13.32 (AppImage)

**Additional context**
Linux file paths use forward slashes, not back slashes. The initial pack files are created in the proper locations, the bug only happens with user saved files.

**Comment by solvedDev** [comment]
The above commit probably fixes this issue. I am not sure whether removing this legacy code line breaks logic elsewhere inside of the app. That's why I didn't remove it before... Gonna need some more testing before I publish a version with this fix

**Comment by solvedDev** [comment]
v0.13.33 has the potential fix in it. Let me know whether the problem still occurs :)

**Comment by CollinScripter** [comment]
Seems to work fine. Thanks!

**Comment by solvedDev** [comment]
Thanks for the report! :D
