### ISSUE TITLE
[Feature] Comment Components/Groups Without Deletion

### ISSUE THREAD

**Issue by CarterPatterson** [bridge-core/bridge.#137]
**Summary**
When debugging an entity, it is sometimes necessary to remove components that will eventually have to be put back in, the easiest way to do this now is to delete the component, save, and then CTRL-Z it back without saving so you don't lose the information. It would be nice to be able to temporarily disable components and groups without losing information.

**Comment by solvedDev** [comment]
![image](https://user-images.githubusercontent.com/33347616/72652460-29084f00-3987-11ea-9111-8ad7c9e328d0.png)
Added for the next update 👍
