### ISSUE TITLE
[Trojan] bridge@0.13.41.exe

### ISSUE THREAD

**Issue by littlepirate3** [bridge-core/bridge.#148]
bridge@0.13.41.exe
Windows Security detects Trojan:Win32/Detplock

**Comment by solvedDev** [comment]
I can confirm that this is an issue but there's nothing I can do about it at the moment. If you're really worried, feel free to browse through the source code which is openly available inside of this repository. You can also compile your own builds or run the application in dev mode; bridge. is completely transparent
