### ISSUE TITLE
[BUG] The `minecraft:timer` Component Offers Incorrect Auto-completion

### ISSUE THREAD

**Issue by CarterPatterson** [bridge-core/bridge.#153]
**Summary**
When making the `minecraft:timer` component, bridge. sees the `time` object as an array but it should just be a decimal value.

**To Reproduce**
1. Create new entity
2. Add `minecraft:timer`
3. Add `time` object
4. Observe bridge. auto-completion

**Observed behavior**
bridge. offers "0, 1" as opposed to the expected "0.0, 0.1, 0.2, etc"

**Expected behavior**
bridge. offers decimals

**Platform (please complete the following information):**
 - OS: Windows 10
 - App Version: 0.13.41

**Comment by CarterPatterson** [comment]
https://bedrock.dev/1.14.0.0/1.14.0.6/Entities#minecraft:timer has it incorrect as well.

**Comment by solvedDev** [comment]
Are you sure that the time ranges are no longer working? It definitely used to work...

**Comment by CarterPatterson** [comment]
I am unsure the specifics, I believe range might still work? But bridge.'s implementation uses an array which does not seem to work.

**Comment by solvedDev** [comment]
![image](https://user-images.githubusercontent.com/33347616/77247681-a70cfe80-6c33-11ea-961c-3e3c9f222ae3.png)
For me it does work, vanilla also uses it. I've added value auto-completions to easier add values to the "time" argument though
