### ISSUE TITLE
[BUG] Cannot change default directory

### ISSUE THREAD

**Issue by GoshDarnedHero** [bridge-core/bridge.#156]
As reported in the discord here:
https://discordapp.com/channels/602097536404160523/603989826982641687/689845455441756222

The source folder is not changing from the default on macOS.  If you need any more diagnostic information, please feel free to reach out here, or on discord (same username)

**Comment by solvedDev** [comment]
Additional information:
![image](https://user-images.githubusercontent.com/33347616/76983484-c9ee9880-693d-11ea-9ca7-1241564b0a3b.png)

**Comment by solvedDev** [comment]
This issue also affects Windows
