### ISSUE TITLE
[BUG] Changing theme doesn't apply for all projects

### ISSUE THREAD

**Issue by pascal541** [bridge-core/bridge.#157]
**Summary**
When the theme is changed, it only works for the currently selected project. When another project is selected, the theme changes to the default theme.

**To Reproduce**
1. Open a project
2. Click on file -> Preferences -> Settings
3. Go to Appearance
4. Change the theme
5. Select another project

**Observed behavior**
Theme goes back to default after switching projects
**Expected behavior**
The theme to stay the same across all projects

**Platform:**
 - OS: Windows 10
 - App Version: v1.1.3

**Additional context**
Not sure if this is intended behavior?

**Comment by solvedDev** [comment]
Thanks a lot for your report! 
However, this is intended behavior. If you wish to have the possibility to also enable themes globally, please open a feature request instead :)
This would require #134 to be added first though

**Comment by pascal541** [comment]
I have created a feature request #158

**Comment by solvedDev** [comment]
Perfect 👍
