### ISSUE TITLE
[BUG] Plugins "crash" the program

### ISSUE THREAD

**Issue by Raycka13** [bridge-core/bridge.#164]
**Summary**
I use the program to make addon (.Bridge)
All work well, but recently I add some plugins to help me for the development of add-ons and when I restart to apply them the screen of the program is now white. I try to delete all folders of .bridge and install the last version (1.2.0), it's loading normally and when it's loads plugins become a white screen.

**Screenshots / File Attachments**
![Screenshot_3](https://user-images.githubusercontent.com/63111883/78374358-0a9c1200-75cc-11ea-84d1-6be599f7f050.png)

**Platform :**
Windows 10
 - App Version: [e.g. 1.2.0]

**Comment by solvedDev** [comment]
Is this issue supposed to be closed already?

**Comment by Raycka13** [comment]
> Ce problème est-il censé être déjà clos?

Hi, I found that it was one of my addons that planted the software.
sorry for inconvenience
