### ISSUE TITLE
[BUG]WEAPON DAMAGE

### ISSUE THREAD

**Issue by mokalax7273** [bridge-core/bridge.#173]
I don't know if it's a mistake but I need help.
I have created 10 new items, (swords), and everything works great except the damage I put on them, I really need help and I really appreciate it.
It is just that, the damage I put on them, for example 9999, within the game is reduced to 1.
help

**Comment by solvedDev** [comment]
You need to have a player.json file inside of your BP and the items will work

**Comment by mokalax7273** [comment]
I have the player.json file with the group of components, events, and the environment_sensor with each of the items.
but it doesn't work the same way.
PLEAS HELP ME

**Comment by mokalax7273** [comment]
> You need to have a player.json file inside of your BP and the items will work

I have the player.json file with the group of components, events, and the environment_sensor with each of the items.
but it doesn't work the same way.
PLEAS HELP ME

**Comment by Calaphron** [comment]
> > You need to have a player.json file inside of your BP and the items will work
> 
> I have the player.json file with the group of components, events, and the environment_sensor with each of the items.
> but it doesn't work the same way.
> PLEAS HELP ME

same
