### ISSUE TITLE
[BUG]ITEMS DO NOT WORK PROPERLY HELP PLIS!!!

### ISSUE THREAD

**Issue by mokalax7273** [bridge-core/bridge.#175]
I really do not have anywhere else to go, as I explained before, when creating custom items such as swords, they do not work as they should, in short they have no harm.
it's like I'm hitting with my hand.
Yes, I have a player.json file, by default of the deck.
Also try putting a player.json file by adding component groups, events and evironment_sensor.
I also used autocompletion for: bridge: item_equipped_sensor, is_equip, minecraft: attack, damage, 9999
previously it worked for me in another addon, but when making a new one it doesn't work anymore,
and I followed all the steps from the previous one, I even tried to copy the player.json file
AND NOTHING
I REALLY NEED YOUR HELP.
I APPRECIATE IT SO MUCH.

**Comment by solvedDev** [comment]
This component is working for everyone else so it's not a bug with the software. Please join bridge.'s Discord server and we can help you there with the usage of the component

**Comment by mokalax7273** [comment]
thank you

**Comment by cccwro** [comment]
The same thing is happening to me and I am using bedrock 1.20.12. Here is the code I am using:`	{
	"format_version": "1.20.10",
	"minecraft:item": {
		"description": {
			"identifier": "stat:venom_excalibur"
		},
		"components": {
			"minecraft:icon": {
				"texture": "stat_venom_excalibur"
			},
			"minecraft:max_stack_size": 1,
			"minecraft:creative_category": {
				"category": "equipment",
				"group": "itemGroup.name.sword"
			},
			"minecraft:display_name": {
				"value": "Venom Excalibur"
			},
			"minecraft:hand_equipped": true,
			"minecraft:weapon": {
				"on_hit_block": {
					"event": "dmg"
				},
				"on_hurt_entity": {
					"event": "dmg"
				},
				"on_not_hurt_entity": {
					"event": "dmg"
				}
			},
			"minecraft:damage": 9,
			"minecraft:can_destroy_in_creative": false,
			"minecraft:durability": {
				"max_durability": 4000
			},
			"minecraft:mining_speed": 1.5,
			"minecraft:enchantable": {
				"slot": "sword",
				"value": 50
			},
			"minecraft:digger": {
				"use_efficiency": false,
				"on_dig": {
					"event": "dmg"
				},
				"destroy_speeds": [
					{
						"block": "minecraft:web",
						"speed": 15,
						"on_dig": {
							"event": "dmg"
						}
					},
					{
						"block": "minecraft:bamboo",
						"speed": 60,
						"on_dig": {
							"event": "dmg"
						}
					}
				]
			}
		},
		"events": {
			"dmg": {
				"damage": {
					"type": "none",
					"amount": 1,
					"target": "self"
				}
			}
		}
	}
}`
It won't deal normal damage to mobs and can't break bamboo and cobwebs properly. Please Help!!!!!!!!!!!!! (By the way, I can't use Discord yet so maybe someone who can use discord could bring it up on the Bridge. discord server and send the answer here. ) Thank you in Advance.

**Comment by outercloudstudio** [comment]
This GitHub is for issues with the bridge program itself. If you have problems with addons, you can join our discord server and ask for help there.
