### ISSUE TITLE
[BUG] Not all fonts render correctly

### ISSUE THREAD

**Issue by StefanJanssen95** [bridge-core/bridge.#178]
**Summary**
I wanted change the font of the editor to [JetBrains Mono](https://www.jetbrains.com/lp/mono/) but it did not work. I tried a few other fonts and some work fine, others don't.  I've tried finding the cause of it, but I don't see any similarities as of now.

**To Reproduce**
1. Go to the settings.
2. Go to "Appearance"
3. Change either "File Font" or "UI Font"
4. Select a few fonts and see a few of them not working and ultimately falling back to the default serif font.

A few fonts that work:
 - Arial
 - Bahnschrift
 - "Bahnschrift Light"
 - Calibri
 - "Calibri Light"
 - Comic Sans MS
 - Consolas
 - Monospace

A few fonts that don't work:
 - "Bahnschrift SemiLight"
 - "JetBrains Mono"

**Platform (please complete the following information):**
 - OS: Windows 10 1909
 - App Version: 1.4.4

**Comment by solvedDev** [comment]
That's weird, both fonts seem to work for me 🤔 

![image](https://user-images.githubusercontent.com/33347616/79635947-722d9200-8174-11ea-9926-3b30c3b95f2a.png)

**Comment by StefanJanssen95** [comment]
What OS are you using? I will try to do some more debugging

**Comment by solvedDev** [comment]
Thanks! 👍
I am also on Windows 10

**Comment by StefanJanssen95** [comment]
Reinstalling the font after a windows update seemed to make it work. Not sure what was wrong but it's not an application issue.
It worked in other applications (including Chromium Edge) so I'm not really sure why it didn't work in Bridge before.
