### ISSUE TITLE
[BUG] Spaces in front of values are removed

### ISSUE THREAD

**Issue by StefanJanssen95** [bridge-core/bridge.#179]
**Summary**
Spaces on the beginning of a value are removed from the visualization tree, they are still in the source files. This is unwanted behaviour, at least for recipes.

**To Reproduce**
1. Create a new recipe
2. Add a hopper recipe pattern
```json
"pattern": [
  "i i",
  "ici",
  " i "
]
```

**Observed behavior**
The space at the beginning of the lines are removed

**Expected behavior**
I expected the bottom line "i" to be aligned in the middle column. 

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/6250246/79635693-a2743100-8172-11ea-8ab6-2e406e285d18.png)

**Platform (please complete the following information):**
 - OS: Windows 10 1909
 - App Version: 1.4.4

**Comment by solvedDev** [comment]
Ah, that's seems to be a purely visual issue, I'll take a look at it 👍 
Thanks for the report!
