### ISSUE TITLE
[BUG] Cannot Save Item Json file

### ISSUE THREAD

**Issue by EdgyBoi2414** [bridge-core/bridge.#180]
**Summary**
When I save an Item it throws an error saying that the location cannot be found.

**To Reproduce**
1. Use a preset to add a new food
2. Add attrributes
3. Try to Save

**Observed behavior**
I checked the console and this was logged.
```
Uncaught (in promise) Error: ENOENT: no such file or directory, copyfile 'C:\Users\user\AppData\Local\Temp\d70db3f7-aab3-438c-8739-5131fad23d87.tmp.json' -> 'C:\Users\user\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\development_behavior_packs\EdgyAddonPack\entities\player.json'
```

It also showed the "Loading" window and it won't close.

**Expected behavior**
For it to save.

**Screenshots / File Attachments**
![Screenshot of Loading and Error](https://i.imgur.com/BAyq0kV.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - App Version: 1.4.4

**Additional context**
N/A

**Comment by solvedDev** [comment]
This is a known issue that's already fixed for the next update 👍

**Comment by EdgyBoi2414** [comment]
Ah ok thank you
