### ISSUE TITLE
[Feature] Auto Command completion for "bridge:item_equipped_sensor" .

### ISSUE THREAD

**Issue by LePichu** [bridge-core/bridge.#183]
**Summary**
a extremely needed & excellent feature bridge. should have, its extremely useful for us content creators. the same completion scheme used for function generation can be used here.

**Additional context/Motivation**
Hey solved, keep up the good work. the only reason for me to get my pc repaired was using bridge.. Thx for the excellent tool you gave us,

**Comment by solvedDev** [comment]
**Context:** Add the same /function auto-completions animation controllers got recently
