### ISSUE TITLE
[BUG] Slow loading & Transition while in New File window.

### ISSUE THREAD

**Issue by LePichu** [bridge-core/bridge.#189]
**Summary**
We need optimisation to everything but specifically the new file window.

**To Reproduce**
This is probably because of my PC.
Just do CTRL+N.

**Observed behavior**
Very, Very Slow.
**Expected behavior**
Instantaneous Transition.

**Platform (please complete the following information):**
 - Windows 7
 - App Version: 1.6.0

**Additional context**

**Comment by finn64** [comment]
*possibly* related, Files won't save and Loading... is indefinite

**Comment by solvedDev** [comment]
I can now confirm that we'll have this fixed for v2!
