### ISSUE TITLE
[BUG] bridge it gives me a strange error the screen becomes transparent when opening the application and nothing is seen

### ISSUE THREAD

**Issue by ALEXYSSSJ4** [bridge-core/bridge.#195]
**Summary**
my bridge it gives me a strange error the screen becomes transparent when opening the application and nothing is seen (it lasts a long time like this and still doesn't see anything)

**To Reproduce**
1. Go to just open bridge

**Observed behavior**
To my bridge it gives me a strange error the screen becomes transparent when opening the application and nothing is see

**Expected behavior**
should open correctly

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**
 - OS: [e.g. Windows 7, 32 bits, 2gb ram]
 - App Version: [minecraft pe 1.14.x]
**note (fix this error please)**

**Comment by solvedDev** [comment]
I sadly cannot reproduce the issue. What do you mean by "the app becomes transparent"? A blank, white screen?

**Comment by Paty007gr** [comment]
I think he means when you open it up and it gets stuck at loading he might have to delete the instalation and install it again it happend to me once on a old version

**Comment by ALEXYSSSJ4** [comment]
Look at this is the bug, only when opening it happens to me (I have already tried to install and uninstall the 3 newest versions and it still happens)
See :
![image](https://user-images.githubusercontent.com/50247095/81331941-50874280-9070-11ea-8a17-12706ea3efb5.png)
![image](https://user-images.githubusercontent.com/50247095/81332019-6d237a80-9070-11ea-9a0d-eb6cf3cfe7c6.png)

**Comment by ALEXYSSSJ4** [comment]
> I sadly cannot reproduce the issue. What do you mean by "the app becomes transparent"? A blank, white screen?

I have been waiting a little over an hour and now the screen has turned white but still does nothing
![image](https://user-images.githubusercontent.com/50247095/81333174-2f275600-9072-11ea-84c4-081d33f32427.png)

**Comment by KingRainbow44** [comment]
If you are running a laptop with integrated graphics, try updating those drivers for said integrated graphics.
