### ISSUE TITLE
No auto fill procedure[BUG]

### ISSUE THREAD

**Issue by THEDARKCENTURY** [bridge-core/bridge.#197]
**Summary**
The drop down menus to auto fill options like description or runtime identifier nothing shows until restart.

**To Reproduce**
1. Create a new entity, item, block or whateve.
2. Clicking the drop downs say nothing until a restart!

**Comment by solvedDev** [comment]
Please make sure that your file was placed in the correct folder and that you‘ve created a first project to get started
