### ISSUE TITLE
[BUG] Creating New Component From bridge. Generates Incorrectly Spelled DIrectory

### ISSUE THREAD

**Issue by CarterPatterson** [bridge-core/bridge.#199]
**Summary**
When creating a new component with bridge., the directory created for components is spelled 'component' while it should be 'components' to match other directories.

**To Reproduce**
1. Use bridge. to create a component
2. Observe file path

**Observed behavior**
File path is project_name/component/[File Name].js

**Expected behavior**
File path should be project_name/components/[File Name].js

**Platform (please complete the following information):**
 - OS: Windows 10
 - App Version: 1.6.0

**Comment by solvedDev** [comment]
This was already fixed in v1.7.0-pre1 :)
