### ISSUE TITLE
[Feature] Telling bridge what and what not folders to scan

### ISSUE THREAD

**Issue by Paty007gr** [bridge-core/bridge.#203]
**Summary**
When you open bridge. It automaicly scans for packs in the minecraft worlds forlder and the development folder

**Alternatives/Considerations**
It would be convenient to have option to not scan the world folder or even telling bridge what and what not folders to scan for addons. This system would be I guess very similar to the option of choosing the default directory in the explorer section in the options

**Comment by solvedDev** [comment]
I am going to ship this request in two phases:
**Phase 1:** An option to disable scanning the world files
**Phase 2:** The ability to precisely set where to load BPs & RPs from

I am going to ship **Phase 1** with the next pre-release
