### ISSUE TITLE
[BUG]:while I am saving the project, it;s always show me the loading screen, and didn't keep stuck in there.

### ISSUE THREAD

**Issue by hmjBill** [bridge-core/bridge.#215]
**Summary**

**To Reproduce**
4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - App Version: [e.g. 0.13.3]

**Additional context**

**Comment by solvedDev** [comment]
Please use the GitHub template
