### ISSUE TITLE
[BUG] Error calling cache

### ISSUE THREAD

**Issue by AcousticJammYT** [bridge-core/bridge.#223]
**Summary**
I tried reinstalling the app on 1.7.0-pre8, but no matter what I do, I can't seem to save my projects. (Resource pack is the only one with this bug)

**Observed behavior**
Unable to save due to an error retrieving the cache.
**Expected behavior**
Saving the data I input.

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/67622111/86085407-0ff2e680-ba6d-11ea-8891-dc006e10b9ff.png)

**Platform (please complete the following information):**
Windows 10, 1.7.0-Pre8

**Comment by Joelant05** [comment]
Do you have a bridge folder in your BP root?
If not you need to create one to fix the issue
In 1.7.0-pre8, that folder doesn't get created when you create a new project, this bug is fixed for the next update
