### ISSUE TITLE
[BUG] Function highlighting

### ISSUE THREAD

**Issue by randommouse** [bridge-core/bridge.#228]
**Summary**
Syntax highlighting broken on mcfunction files.

**To Reproduce**
1. Create mcfunction
2. Use multiple selector arguments
3. Use selector tag="$tagname" 

**Observed behavior**
Syntax highlighting gets messed up when using "" in selector arguments
**Expected behavior**
Syntax highlighting should treat "" as part of argument name.

**Platform (please complete the following information):**
 - Windows 10]
 - latest build

**Additional context**

**Comment by solvedDev** [comment]
Thanks for the report! Are you using bridge. v1.6.0 or one of the v1.7.0 pre-releases?

**Comment by randommouse** [comment]
Pre-release

**Comment by randommouse** [comment]
Yes, 9.

**Comment by solvedDev** [comment]
@randommouse 
Is this the issue you're describing? If not, can you please attach a screenshot?
![image](https://user-images.githubusercontent.com/33347616/87147676-54705480-c2ad-11ea-9715-f390bac39882.png)

**Comment by randommouse** [comment]
that is the issue
