### ISSUE TITLE
[BUG] Save-as entities do not correctly manage Animation Controllers

### ISSUE THREAD

**Issue by Jbenisek** [bridge-core/bridge.#231]
**Summary**
When save-as entities to new entities the script / animate pointing to animation controllers DO NOT correctly duplicate and link to the new files. They also mess up the new files and show the hidden bridge command IDs and cause issues changing any commands without going into AC. Once this happened script/animate show up in entity file but DO NOT do anything or affect the file's code other than adding more scripts calls to the same entity over and over cause each event to file as many times as there are bridge_execute_commands. I have 3 before I had to fix it. Comments Also don't transfer when duplicated.
"scripts": {
				"animate": [
					"bridge_execute_commands",
					"bridge_execute_commands"
				]
			},

**To Reproduce**
Duplicate Entity with a new name. Update entity identifier. 
Save-as new entity name. Update entity identifier.

**Observed behavior**
Deleting these calls script/animate or changing them in bridge did NOT affect the main hidden calls in json. Only editing the code json outside bridge fixes it. 

**Screenshots / File Attachments**
![displaycab_bridge_bug_a_07112020](https://user-images.githubusercontent.com/6779509/87230532-fce5ed80-c36d-11ea-831e-a17f9fdb6c32.png)
![sh_bridge_bug_a_07112020](https://user-images.githubusercontent.com/6779509/87230533-feafb100-c36d-11ea-8b6b-d7cf885e8f59.png)
![armchair_bridge_bug_b_07112020](https://user-images.githubusercontent.com/6779509/87230534-00797480-c36e-11ea-8ee5-7b98f880d694.png)
![armchair_bridge_bug_a_07112020](https://user-images.githubusercontent.com/6779509/87230535-01aaa180-c36e-11ea-8cf3-1b1feabbfb91.png)

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - App Version: [e.g. 1.7.0pre9] But was in 1.6 release. Started there and was reported to discord help. May 9th, 2020.
 
Reported to help https://discordapp.com/channels/602097536404160523/603989805763788800/725571669866840124
https://discordapp.com/channels/602097536404160523/603989805763788800/708818430979211335

**Comment by Jbenisek** [comment]
As far as the creation of the animation controllers. Sometimes they were created but many aren't. I'm not sure when they are created or not. But I duplicated files for a lot of entities and only maybe 1/4 have AC created in their names.

**Comment by Jbenisek** [comment]
Some entities in this same project don't show in code script/animations at all. Should this code be in the json code at all?
![image](https://user-images.githubusercontent.com/6779509/87232497-be0b6400-c37c-11ea-8a15-010f431ba74c.png)

**Comment by Jbenisek** [comment]
I went through and clean them all up in code outside bridge and now all of them show the IDs and are painful to work in. 
![image](https://user-images.githubusercontent.com/6779509/87235022-86a8b180-c394-11ea-955c-624aba35bcad.png)

**Comment by Jbenisek** [comment]
As I do more testing I think duplicate is fixed but and save as is the only issue. I think my duplicate issues are from before the issue was fixed and I never fixed the results of that bug. 

I have a video of the save as process but don't want to share it publically if you need please contact me directly.

**Comment by solvedDev** [comment]
I believe "save as" never supported duplicating the cache files. That's due to the fact that you can save the file literally anywhere and we cannot mirror this flexibility with our cache structure.

This should hopefully "fix itself" once we remove the cache system

**Comment by Jbenisek** [comment]
Any eta when that will be and the effects on current projects?

**Comment by solvedDev** [comment]
See my comment on #233
