### ISSUE TITLE
[BUG] Creating folder in Bridge and dragging moving entity in to it give error on open/change/save no file found

### ISSUE THREAD

**Issue by Jbenisek** [bridge-core/bridge.#232]
**Summary**
When I create a subfolder and drag an entity into it from the entity folder or others. It shows there correct, but once opened, edited it wont save. Give error 0.chache error calling omegachche.save(..): ENOENT: no such file or directory, open. If I put the file back where it was it opens and saves correctly. I've tried closing program, refreshing, reloading cache, making the folder myself in the bp folder doesn't fix as a cached folder isn't then created too.

**To Reproduce**
1. Create sub folder under entities
2. Drag already made entity in to folder
3. Open entity, make change, save
4. Gives error and wont save. Save as to another folder works.

**Screenshots / File Attachments**

![image](https://user-images.githubusercontent.com/6779509/87232017-fc068900-c378-11ea-957d-fc4826dea4f5.png)
![image](https://user-images.githubusercontent.com/6779509/87232077-80f1a280-c379-11ea-9f20-6304d3c9c744.png)

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - App Version: [e.g. 0.13.3] 1.7.0pre9

**Additional context**
I did NOT see this bug in 1.6. This is new as of upgrading to 1.7.0 pre9 for 1.16 support.

**Comment by solvedDev** [comment]
Thanks for the report, I'll take a look at it 👍

**Comment by Jbenisek** [comment]
This also seems to be what breaks the bridge IDs as well. If I leave my entities files in the entities folder they look correct but if I move them to a sub folder they show the IDs. If I move them back they then hide the IDs and look correct again. This is frustrating as I have a lot of entities and need to org them in subfolders. This seems new as of 1.7.0pre9 and I don't think this was in 1.6

**Comment by solvedDev** [comment]
While working on this issue, I noticed that it also affected duplicating/renaming files. The fix should be part of the next pre-release (releases later this week) 👍
