### ISSUE TITLE
[BUG] When duplicating or save-as to new entity bridge version don't reset

### ISSUE THREAD

**Issue by Jbenisek** [bridge-core/bridge.#233]
**Summary**
When duplicating or save-as to new entity bridge version cont to count and don't reset for the new file. 
Is this a bug or by design? 

**To Reproduce**
Duplicate entity to new entity. Bridge versions don't reset for new file. 

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - App Version: [e.g. 0.13.3] 1.7.0 pre9

**Additional context**

**Comment by solvedDev** [comment]
This is similar to #231. I am not sure whether it's worth fixing the issue since we do not want to keep the cache system any longer. 
Thanks for the very detailed report though :)

**Comment by Jbenisek** [comment]
Any idea when the cache system will be removed and the effects on current projects?
Will any features be lost?

**Comment by solvedDev** [comment]
I am aware that bridge. is used by companies producing Marketplace content and we will keep full backwards compatibility where it's possible.

Currently, we plan to provide our users with the option to convert current bridge. projects to the new format. The main difference will be that all files will be saved in an uncompiled state so you can edit them with any editor. Upon saving a file with bridge. or running the new "compile" task, bridge. will take all of your files, compile them and store them inside of the com.mojang folders.

There's no release date for this feature yet, it's a pretty big change and we're not sure how exactly we'll approach the implementation. This is the big next thing for bridge. I've been talking occasionally about. The move will e.g. enable us to fix some bugs Minecraft introduces by "compiling away the problematic code".

**Comment by Jbenisek** [comment]
This seemed to get better and I was able to work around it. But today it's back and really causing issues. This really causes issues. Everything is working so well then this hits a file and really slows down dev. Was just trying to duplicate an entity. A few entity temples that were fine now are broken like this out of no where.
Moving the entity in to a sub folder seems to be a main cause. But I have 200 entities and really need subfolders.

**Comment by solvedDev** [comment]
Sub folders should be supported now. Can you tell me whether it just fails silently or do you see an error inside of the console?
