### ISSUE TITLE
[BUG] bridge ID rename bug is fix if in main entity folder but not sub folders

### ISSUE THREAD

**Issue by Jbenisek** [bridge-core/bridge.#238]
**Summary**
When duplicating or renaming an entity in the entity folder it work correctly and I can drag entities to sub folders now without error. However, if I then rename/duplicate them in those subfolders it breaks them and shows IDs again.

**Comment by Jbenisek** [comment]
![image](https://user-images.githubusercontent.com/6779509/87611782-241e2100-c6c6-11ea-93a0-b45fec2010ae.png)
also still having some issue with rename. Because I could use the template folder I deleted it. Then went to duplicate a file that was in it but moved out. I duplicated then tried to save and got this error.

**Comment by solvedDev** [comment]
Okay, I've done some pretty thorough tests for renaming, moving & duplicating files and everything seems to be working fine now 🎉 
Thanks a lot for the reports on this subject!
