### ISSUE TITLE
[BUG] Software not installing through exe file

### ISSUE THREAD

**Issue by utkgamer** [bridge-core/bridge.#242]
**Summary**
I downloaded exe file of bridge and when I install it, it says internet connection issue, I've tried it several times even with a very good internet connection, but it says the same everytime.

![Screenshot (240)](https://user-images.githubusercontent.com/67854826/87847562-e522e200-c8f6-11ea-9a72-7c6994f210a3.png)

**Platform (please complete the following information):**
 - OS: Windows 10 Pro
 - App Version: 10.0.18363

Unable to install, please fix ASAP

**Comment by solvedDev** [comment]
The installer is sadly something we have no control over. We rely on electron-builder producing correct executables.
