### ISSUE TITLE
bridge:weapon_damage not working

### ISSUE THREAD

**Issue by Calaphron** [bridge-core/bridge.#246]
I tried to make a weapon "knife", with bridge. Everything about the item works fine until i hit an enity. It does the exact same damage as my hand. It just ignored the "bridge:weapon_damage" value. I don't know what else I'm doing wrong.

**Comment by dominique-bautista** [comment]
did you put hand equiped true?

**Comment by solvedDev** [comment]
We currently cannot reproduce the issue. Feel free to join the Discord server and send me your behavior pack so I can take a look at what could be going wrong for you!
