### ISSUE TITLE
[BUG] Function compiler ignores multiple spaces

### ISSUE THREAD

**Issue by rebrainertv** [bridge-core/bridge.#248]
**Summary**
When writing functions (and probably other things, but I haven't checked) in bridge., any groups of multiple spaces will be compressed down into a single space in the editor. So instead of getting your desired `a______b` (this glitch is on GitHub too so I have to use underscores) you end up with `a_b`. 

**To Reproduce**
1. Create a new project
2. Add a function
3. Add in the command `title @s actionbar a______b` with a space in place of the underscores
4. Add the pack to a world and run the function
5. Observe result

**Observed behavior**
In the editor, bridge. will keep the spaces you typed but when compressing then into a .mcfunction, the .mcfunction file does not include the spaces.
**Expected behavior**
The text should show up exactly as you typed it.

**Platform (please complete the following information):**
 - OS: **Windows 10**
 - App Version: **1.7.1**

**Additional context**
When developing in HTML I had this problem before. It seems that this issue is a fault of HTML/JavaScript or maybe even the Chromium Engine. I remember `&nbst;` would create a normal space that is unaffected by this glitch. Hopefully you find that helpful. Thanks!
-ReBrainer

**Comment by solvedDev** [comment]
I think I've fixed that for the next update :)
