### ISSUE TITLE
[BUG] pack.description doesn't show up correctly in the BP menu

### ISSUE THREAD

**Issue by Chikorita-Lover** [bridge-core/bridge.#264]
**Summary**
When selecting an addon to edit in the large dropdown menu, `pack.description` doesn't show the corresponding name given in `en_US.lang`.

**To Reproduce**
1. Set an addon's description in the manifest to `pack.description`
2. Define `pack.description` in the BP `en_US.lang`
3. Open the addon menu
4. Observe result

**Observed behavior**
The description under the addon icon just says `pack.description`.
**Expected behavior**
The description under the addon icon should take the defined text for `pack.description` in the `en_US.lang`.

**Screenshots / File Attachments**
![Addon menu](https://user-images.githubusercontent.com/68617589/91356378-2e4b3900-e7b5-11ea-9c6b-6e90b8fc1f43.png)
![Cave update manifest](https://user-images.githubusercontent.com/68617589/91356499-6783a900-e7b5-11ea-8207-3e1d4ffc2590.png)
![Coffee addon manifest](https://user-images.githubusercontent.com/68617589/91356428-49b64400-e7b5-11ea-8d2a-9178b2147e68.png)

**Platform:**
 - OS: Windows 10
 - App Version: bridge. 1.7.4

**Comment by Joelant05** [comment]
This will be implemented in the next update :)
