### ISSUE TITLE
[BUG] Spawn Egg LANG file autocompletions are missing a period

### ISSUE THREAD

**Issue by Chikorita-Lover** [bridge-core/bridge.#265]
**Summary**
The LANG file autocompletions for Spawn Eggs are incorrect and are missing a `.`.
**To Reproduce**
1. Create an entity
2. Open a LANG file
3. Start typing in `item.`
4. An incorrect option for a Spawn Egg autocompletion pops up

**Observed behavior**
The autocompletion for Spawn Egg names is missing a `.`.
**Expected behavior**
The autocompletion should have a `.` between `entity` and the project's namespace.

**Screenshots / File Attachments**
![Screenshot](https://user-images.githubusercontent.com/68617589/91363536-73c23300-e7c2-11ea-934f-680a7b894fe0.png)

**Platform:**
 - OS: Windows 10
 - App Version: bridge. 1.7.4

**Additional context**
I have noticed this issue since LANG autocompletions were initially added.

**Comment by Joelant05** [comment]
Thanks for the report, this is fixed for the next update :)
