### ISSUE TITLE
[BUG] Custom Global Plugins will randomly not load

### ISSUE THREAD

**Issue by Gekocaretaker** [bridge-core/bridge.#266]
A global plugin I made (with help from the developers) sometimes will not load and this can cause problems with compiling files that uses the plugin.

I noticed that the plugin will only load if I check the plugins page of bridge. first. Otherwise the plugin will not load.
The plugin also will not be visible if any edits are made to it unless the plugin folder is moved out and back into the folder.

I added the plugin for testing the bug.

 - OS: Windows 10
 - App Version: 1.7.4
[SimplyJson.zip](https://github.com/bridge-core/bridge./files/5147830/SimplyJson.zip)

**Comment by solvedDev** [comment]
Can you give me some exact steps to reproduce the issue? The plugin loads completely fine for me... 🤔

**Comment by Gekocaretaker** [comment]
How I got the error is if I have edited the plugin, have not checked to see if it has loaded, and go straight to trying to use it.
Also I have noticed that it keeps making the theme Chikorita-Lover made not load as well. And I haven't edited it at all.

**Comment by solvedDev** [comment]
After editing a plugin, you need to refresh the application (explorer tab). Did you do that?

**Comment by Gekocaretaker** [comment]
Oh. I didn't. That might have been the problem.

**Comment by solvedDev** [comment]
I will close this issue then. Feel free to reopen it if you have new findings 👍
