### ISSUE TITLE
[BUG]Soul Campfire Tag not working 

### ISSUE THREAD

**Issue by FallenToast** [bridge-core/bridge.#269]
**Summary**
So basically I created a recipe that you specifically need a soul campfire for. Putting the ingredient on the soul campfire doesn't work or is accepted. There is a workaround in which you also need a normal campfire in the tags.

**To Reproduce**
Create a new recipe. Under tags only put Soul Campfire. Go in game. Your custom recipe doesn't work.
**Platform**
Windows 10

**Comment by Chikorita-Lover** [comment]
This is not a bridge. bug, but an error with your addon. Please use the issues tab for feature requests and bugs only.
