### ISSUE TITLE
[Feature] Add A Publisher

### ISSUE THREAD

**Issue by CarterPatterson** [bridge-core/bridge.#272]
**Summary**
Without a publisher, Windows always blocks update/installation attempts. Adding a publisher will fix this issue.

**Alternatives/Considerations**
Maybe it can't be done on the installer? I think it can.

**Additional context/Motivation**
![image](https://user-images.githubusercontent.com/42452101/93810940-3788c380-fc04-11ea-91dd-4d3e4a41e177.png)

**Comment by ENDERZOMBI102** [comment]
this isn't possible as it requires a paid license, there was a discussion some time ago on this argument, but i don't remember how it finished

**Comment by CarterPatterson** [comment]
Unfortunate!

**Comment by solvedDev** [comment]
We have a different solution for the problem in mind though. Should hopefully be fine with bridge. v2 :)
