### ISSUE TITLE
[BUG] minecraft:digger auto-completions

### ISSUE THREAD

**Issue by MaybeLess** [bridge-core/bridge.#274]
"minecraft:digger" dont show up as a component

Basically:
1. Create a block, fill up what you want:
2. Open the components "menu", and the minecraft:digger, wich is a component, doesn't appear.

![image](https://user-images.githubusercontent.com/71945166/94349183-bcb31480-0018-11eb-933a-910ff6a5d353.png)

 - OS: Windows 10
 - App Version: 1.7.7

**Comment by Joelant05** [comment]
🤔 It shows up for me, does it show up if you just restart bridge?

**Comment by solvedDev** [comment]
Ah, you almost definitely need a project so we can load the correct auto-completions for it

**Comment by MaybeLess** [comment]
> 🤔 It shows up for me, does it show up if you just restart bridge?

I tried it, and tried to reinstall the app too, it just dont work for me

**Comment by Joelant05** [comment]
> Ah, you almost definitely need a project so we can load the correct auto-completions for it

As said here ^^^, you need to create a project
