### ISSUE TITLE
No Behavior Packs Detected

### ISSUE THREAD

**Issue by MR-QUACK94** [bridge-core/bridge.#276]
**_When i open bridge it says no behavior packs detected, Do i have to have ,inecraft installed on my pc to use bridge???_**

**Comment by Chikorita-Lover** [comment]
You just need to create a behavior pack within bridge. I have seen people use bridge. with _Minecraft_ on a different platform, but I'm not sure how it is done.

**Comment by MR-QUACK94** [comment]
I know how do do this, but it wont let me click the "create" button to
create a ne behavior pack.

**Comment by Joelant05** [comment]
You need to input the project name, description and target version first

**Comment by MR-QUACK94** [comment]
I have done that, is there a chance you can send me a video or screen shot
of how to do it?

**Comment by Joelant05** [comment]
Check out this guide: https://bridge-core.github.io/editor-docs/getting-started/#creating-a-project
