### ISSUE TITLE
[BUG] Auto-completion & Typing Manually Doesn't Work With Block Trigger Components.

### ISSUE THREAD

**Issue by ThePillager** [bridge-core/bridge.#282]
Hello !
There's A Bug With Block Trigger Components , Auto-completion Doesn't Even Work & Typing Manually Also Doesn't Work with these Components. I was Just Preparing For The Next Update.

See you soon,

The Pillager

**Comment by Joelant05** [comment]
Have you set the format version to 1.16.100?

**Comment by ThePillager** [comment]
Yes

**Comment by Joelant05** [comment]
What version of bridge are you in? and could you send screenshots of the file

**Comment by ThePillager** [comment]
Im On The Latest v1.7.9
![image](https://user-images.githubusercontent.com/61835816/96460341-04454e80-121b-11eb-9f08-3d163f14635c.png)
As You Can See The Editor Doesn't Show Anything Unless You Write Something & Forced It Into A Value.

**Comment by Joelant05** [comment]
I see the problem, it will be fixed asap, thanks
