### ISSUE TITLE
[BUG] It wont show any of the addons that are in my com.mojang files and when i create a new project me screen goes all white.

### ISSUE THREAD

**Issue by kayracam** [bridge-core/bridge.#287]
**Summary**
I cant see any of the files from the com.mojang files or edit them and if i mage to create a new project it makes my screen go all white
![Screenshot (73)](https://user-images.githubusercontent.com/73849837/97906312-6caf2800-1d11-11eb-94d6-a03e2726ee60.png)
![Screenshot (74)](https://user-images.githubusercontent.com/73849837/97906318-70db4580-1d11-11eb-9044-add66514aa8c.png)

**Comment by solvedDev** [comment]
Which operating system are you using? Can you provide miore information? 
There's a reason why we have the bug reporting template ;)

**Comment by kayracam** [comment]
Nevermind I figured out how to do it, and the problem was caused by the default directory, so I had to change something in it because i moved my com.mojang file. Also I am using Windows 10 Home.

**Comment by solvedDev** [comment]
Alright, glad you figured it out :)
