### ISSUE TITLE
[BUG] Bridge Setup Hang

### ISSUE THREAD

**Issue by DurianCube** [bridge-core/bridge.#297]
**Summary**
After run the bridge-web-setup-1.7.16. The installation stuck on downloading packages.7z for hours

**To Reproduce**
1. Go to 'bridge-web-setup-1.7.16'
2. Click on 'run as administrator '
3. Wait until the installation stuck on downloading package. 7z
4. Observe result

**Observed behavior**
Long loading of downloading package.7z
**Expected behavior**
Expecting a easy and clean setup without to wait for hours 
**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - App Version: [e.g. 1.7.16]

**Additional context**
My Internet speed is 200mbps and working fine to download, stream, or playing games

![IMG_20201216_182924](https://user-images.githubusercontent.com/19385005/102337157-151d0100-3fcd-11eb-99e5-9a731f495e23.jpg)

**Comment by Jsandtooper** [comment]
I have experienced the same issue, very frustrating. Hope this can be resolved soon

**Comment by solvedDev** [comment]
The installer experience is sadly completely out of our hands as we're only maintaining the core app. We'll have this resolved with bridge. v2 though as we're using a different distribution method

**Comment by Jsandtrooper** [comment]
Good to hear, can't wait for Bridge v2!
