### ISSUE TITLE
[Feature] Code view

### ISSUE THREAD

**Issue by Tschipp** [bridge-core/bridge.#299]
**Summary**
I would really appreciate a code view for files, where I can directly see and edit the raw JSON. 

**Additional context/Motivation**
I find myself wanting to switch to something like VSCode when changing a lot of stuff or copying things from existing entities (which aren't necessarily in the same project). But since that messes with bridge's cache, that is almost never a good idea. Of course, reason for not implementing this is because you want to prevent people from writing erroneous JSON files, which I understand. I just think it is a bit cumbersome sometimes, especially when I'm copying things from other previous works.

**Alternatives/Considerations**
I can't really think of any alternatives.

**Comment by Chikorita-Lover** [comment]
This is already planned for version 2.0.0

**Comment by solvedDev** [comment]
Thanks for the suggestion! We are going to go text editing first for bridge v2 which is in the works right now 👍
