### ISSUE TITLE
[BUG] unable to launch AppImage from Debian Buster

### ISSUE THREAD

**Issue by ronoaldo** [bridge-core/bridge.#305]
**Summary**
After downloading bridge-1.7.18 AppImage file, making it executable, the execution fails with a sandboxing error message on Debian Buster.

**To Reproduce**
1. Download the released .AppImage file version 1.7.18 (x86_64)
2. Save the file and mark it executable
3. Launch it executing from a terminal session: `./bridge....AppImage`
4. Observe result

**Observed behavior**

The application will fail to start with the following error message:

```shell
~/Applications$ ./bridge-1.7.18-x86_64_67513ebde039fd8f5ae10e809a46ee7a.appimage 
[13925:0118/122433.434348:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_bridgeXXrqlF/chrome-sandbox is owned by root and has mode 4755.
```

**Expected behavior**

The application to launch successfully under Debian.

**Platform (please complete the following information):**

- OS: Debian Buster + Backports Kernel and Video Drivers
  ```shell
  $ lsb_release -a
  No LSB modules are available.
  Distributor ID: Debian
  Description:    Debian GNU/Linux 10 (buster)
  Release:        10
  Codename:       buster
  ```
- App Version: 1.7.18-x86_64 (AppImage release)

**Comment by solvedDev** [comment]
Hello 👋 
Thanks for the very detailed report! We are currently in the process of deprecating our electron application in favor of a PWA. This should smooth out the installation process on all platforms significantly and it is also why won't invest in fixes for the existing infrastructure anymore. 
You can follow the development process of [bridge. v2](https://github.com/bridge-core/editor) here!

**Comment by ronoaldo** [comment]
Thanks!

I'm new to Minecraft and add-ons in general, and was pointed to use Bridge so I'm looking for it by the awesome discord community behind bedrock.dev.

The best path would be to test/try the v2 now so I can also help ironing it out?

**Comment by solvedDev** [comment]
v2 is still pretty heavy WIP. We are yet to get project creation and file creation in and there are a few more important key features missing. 
We are always open to contributions though :D

**Comment by solvedDev** [comment]
Here's our Discord server in case that you want to move the conversation :)
https://discord.gg/uj8K2S9

**Comment by ronoaldo** [comment]
Got it, since the v1 is no longer receiving updates I'll try v2 from now on so maybe I can also help with that as I'm still learning stuff. Closing this and moving to discord to discuss.
