### ISSUE TITLE
[Feature] Don't Display Ignored Errors on Parent Objects

### ISSUE THREAD

**Issue by CarterPatterson** [bridge-core/bridge.#306]
**Summary**
Hide error should hide the error notification on parent objects of whatever object the error is for.

**Additional context/Motivation**
This is purely nitpicking and maybe not worth the time.

**Comment by 7dev7urandom** [comment]
Thanks for the idea! However, all development on bridge. v1 has been stopped as it is in a reasonably stable state in favor of pushing out bridge. v2 as soon as possible. As you said, this issue is probably not worth the time since bridge. v1 is on its way out.
