### ISSUE TITLE
[BUG] Creating Preset Overwrites Existing Files

### ISSUE THREAD

**Issue by DeeFeeCee** [bridge-core/bridge.#310]
**Summary**
Using Tools > Presets to create a new object overwrites any premade files that share the same name, destroying progress.

**To Reproduce**
1. Create test.png in RP\textures\items
2. Go to Tools
3. Click on Presets
4. Create item "text"
5. Observe overwritten image file

**Observed behavior**
bridge. overwrites files added before preset creation
**Expected behavior**
bridge. should not overwrite preexisting files/asks to overwrite them

**Platform**
Win10
bridge. v1.7.18

**Comment by solvedDev** [comment]
We've fixed that with bridge. v2 a week ago :)
