### ISSUE TITLE
[BUG] Under the item component "minecraft:digger" and tag "destroy_speeds", the "speed" tag is only in the dropdown outside the arrays

### ISSUE THREAD

**Issue by ManosSef** [bridge-core/bridge.#312]
**Summary**
I know the title was a little confusing. Let me explain. So, when I added the "minecraft:digger" component to one of my custom items, and added the "destroy_speeds" tag under it, the dropdown would not only show me the option to add an array ("0"), but it would also suggest that I added the "speed" tag. When I looked into the vanilla items, I saw the "speed" tag being under the array, but in my custom items, bridge would not suggest that I added it under the array.

**To Reproduce**
1. In a project's behavior pack, click the button that once hovered over says "New File".
2. Scroll down the icons to the left and click on the sword that says "Item".
3. The name of the item does not matter, so create the item.
4. After adding the necessary tags "format_version" and "minecraft:item" containing "description", add a "components" tag.
5. Add the component "minecraft:digger", and the "destroy_speeds" tag under it.
6. Select the "destroy_speeds" tag and click on the text box that says "Add object".
7. Look at what the dropdown suggests.

**Observed behavior**
The "speed" tag appeared in the dropdown when "destroy_speeds" was selected.
**Expected behavior**
The "speed" tag would appear in the dropdown when an array under "destroy_speeds" was selected.

**Screenshots / File Attachments**
![bug](https://user-images.githubusercontent.com/65536780/106148481-c2b13180-6181-11eb-9630-3fe6e92cfba3.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - App Version: 1.7.18

**Additional context**
It's only a dropdown issue, I could just add the tag to the array correctly and bridge wouldn't show me any error.

**Comment by Joelant05** [comment]
Thanks for letting us know! This will be fixed in the next data update
