### ISSUE TITLE
[BUG]I'm banned on discord sad 😔 

### ISSUE THREAD

**Issue by shortpupper** [bridge-core/bridge.#315]
im sorry how do i get un banned i was banned like 6-4 months ago 

this is so bug

edit: im banned on discord and i need help

**Comment by Chikorita-Lover** [comment]
If you tell me your Discord username + ID, I could check why you were banned

**Comment by shortpupper** [comment]
ok it is 
mine5765#3614


> If you tell me your Discord username + ID, I could check why you were banned
> 
> Although I wouldn't say this is the best place to put this, then again, where else would you?

mine5765#3614

**Comment by Chikorita-Lover** [comment]
Oh yeah, you were initially banned for an inappropriate name. I also remember you had DMed many others, asking for addon help (me included).

**Comment by shortpupper** [comment]
Oh well I forgot why I was banned for if ask me, and thank you for taking time out of you day to help me.

**Comment by solvedDev** [comment]
This place is not the correct way to appeal and/or complain about Discord server stuff!

**Comment by shortpupper** [comment]
then where do i appeal
