### ISSUE TITLE
[BUG] Loading files in Bridge alters function

### ISSUE THREAD

**Issue by Tschipp** [bridge-core/bridge.#320]
**Summary**
When copying files with certain syntax commonly seen in animation controllers and then opening those files in bridge, it can cause a change in the syntax which causes the animation controllers to no longer function.

**To Reproduce**
1. Open a file in bridge which contains a name-value pair in which the value is a numerical string, like "1.0". 
2. Bridge will convert the numerical string to a number, which alters the behavior of the file (it shouldn't imo, I even somehow remember it working with numbers as well as strings, so I'm not sure what's going on here)

**Observed behavior**
This is the original file to the left and the file when opened and saved with bridge to the right:
![image](https://user-images.githubusercontent.com/11649893/107625793-24cb6580-6c5d-11eb-902d-1c2dc110ac36.png)

This was the file used for this: https://pastebin.com/H7nLZnp4

**Expected behavior**
Bridge to preserve file behavior.

**Screenshots / File Attachments**
Already above.

**Platform (please complete the following information):**
 - OS: Windows 10
 - App Version: 1.7.16

**Comment by solvedDev** [comment]
This happens due to bridge. v1's automatic type detection: "1.0" is a valid number and bridge. therefore saves the string as a number. That's why bridge. proposes "(1.0)"/ "(0.0)" instead.

v2 won't have this issue though :)

**Comment by Tschipp** [comment]
Ah, alright. What is the progress on v2?

**Comment by solvedDev** [comment]
We're actually releasing the first alpha this weekend to gather some initial feedback. This alpha will be far away from feature complete but we're expecting a full release sometime in Q1 or early Q2 this year.

**Comment by Tschipp** [comment]
Ah wow that's awesome!
