### ISSUE TITLE
[BUG]Item Icons broken

### ISSUE THREAD

**Issue by mikekan13** [bridge-core/bridge.#326]
Item icons will not display in game for custom made items.

**Comment by 7dev7urandom** [comment]
This sounds like either a mistake by you or possibly a Minecraft bug, which we have no control over. I'm going to close this, but if you believe this is a bridge. bug, please supply some more information.

**Comment by solvedDev** [comment]
Make sure that you are/you are not using client items depending on the Minecraft version you use.
