### ISSUE TITLE
Custom items do not show texture/are invisible

### ISSUE THREAD

**Issue by JoReSmi** [bridge-core/bridge.#333]
I have been trying to create custom items, and when I tried to make a custom pickaxe, the texture is not there. It functions as intended, but the item doesn't show, it's invisible. I have watched 3 different tutorials, and I have redone it more than a dozen times. Nothing works. Also, please don't refer me to discord, I don't have it and my parents won't let me get it.

**Comment by JoReSmi** [comment]
It works for making a new block. The texture registers for that.

**Comment by JoReSmi** [comment]
Is it possible that this is something wrong with my computer? That my computer isn't strong enough to do this?

**Comment by Chikorita-Lover** [comment]
This isn't a bridge. bug, I recommend using the discussions for this. https://github.com/bridge-core/bridge./discussions/categories/add-on-q-a

**Comment by JoReSmi** [comment]
Thanks
