### ISSUE TITLE
Can't install properly.

### ISSUE THREAD

**Issue by senzaiwa** [bridge-core/bridge.#339]
I've been experiencing this problem for about 2 days now... I don't know if its only my problem but.. the setup is stuck at "Downloading package. 7z" and it says it is my connection that is the problem but my internet is doing just fine.. it was okay when i installed it for the first time but now I'm reinstalling and i cant seem to do it... is there a problem on how i do it? if so please help me.

**Comment by solvedDev** [comment]
People ran into this problem from time to time and we're yet to hear back from someone who solved the issue. All I can tell you is the typical stuff: Force quit the installer, manually uninstall bridge., restart your computer and download a new installer for bridge.

bridge. v2 doesn't have this problem and you can try it out now here: https://bridge-core.github.io/editor/

**Comment by senzaiwa** [comment]
Where is the file path for it? I'm using Windows

**Comment by solvedDev** [comment]
The file path for what?

**Comment by senzaiwa** [comment]
the file path for the files..of bridge.. i cant find it

**Comment by solvedDev** [comment]
You can just uninstall bridge. like any other Windows app: `Right-click` > `Uninstall`

**Comment by senzaiwa** [comment]
ok thanks.. was succesfully installed now. :)
