### ISSUE TITLE
[BUG] Remote Data Version 1.1.30 cannot open features JSON

### ISSUE THREAD

**Issue by DerpMcaddon** [bridge-core/bridge.#342]
When trying to open feature files on Remote Data 1.1.30 it won't open the files and show a "Type Error : Cannot convert undefined or null to object" splash
![bridgebug](https://user-images.githubusercontent.com/83530851/116805502-3122d880-ab51-11eb-9c84-0b4aedb91ab4.png)

**Comment by solvedDev** [comment]
An update should be available any minute now 👍
