### ISSUE TITLE
Problem when creating new item [BUG]

### ISSUE THREAD

**Issue by LionLight95** [bridge-core/bridge.#349]
Basically when I create an item the "format version" isn't with the "minecraft:item" any fixes available

**Comment by solvedDev** [comment]
Thanks for the report! 
@Joelant05 can you take a look? Sounds like it might have been caused by our latest data update

**Comment by Joelant05** [comment]
I'll take a look soon 👍

**Comment by solvedDev** [comment]
Closed by 4439017aeaa2e3b9868f61120594c10c758734ea
