### ISSUE TITLE
Saying "Invalid argument not valid semver (" received)" whenever a new file is made[BUG] 

### ISSUE THREAD

**Issue by RazorWave** [bridge-core/bridge.#353]
**Summary**
Whenever a new file is made it comes up with the error "Invalid argument not valid semver (" received)", however it still lets you make the addon but it doesn't show on Minecraft.
**To Reproduce**
4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - App Version: [e.g. 0.13.3]

**Additional context**

**Comment by solvedDev** [comment]
This has been fixed already. Restart bridge. & the fix should take effect.

 For the future: Please follow the issue template!
