### ISSUE TITLE
[BUG] Error upon using lang auto-completions

### ISSUE THREAD

**Issue by Raconteur37** [bridge-core/bridge.#361]
**Summary**

**To Reproduce**
4. Observe result

**Observed behavior**
A clear and concise description of what happened

I wrote my code to try to change the name of my item, but this error came up and my item doesn't appear.

**Expected behavior**

Trying to change the display name for an item. 

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - App Version: [e.g. 0.13.3]

Windows 10

**Additional context**
![Capture](https://user-images.githubusercontent.com/69336066/121266240-c36c7980-c87f-11eb-8f61-d527291793f6.PNG)

**Comment by solvedDev** [comment]
The issue itself is not connected to your item not showing up in-game. For more support on that, feel free to join our Discord. We'll take a look at the error though, thanks :)

**Comment by Raconteur37** [comment]
> The issue itself is not connected to your item not showing up in-game. For more support on that, feel free to join our Discord. We'll take a look at the error though, thanks :)

I fixed the error by going into the json renderer and changing code, thank you.
