### ISSUE TITLE
[FEATURE] Feature Templates Need Updating

### ISSUE THREAD

**Issue by crovono** [bridge-core/bridge.#362]
At minimum, the single block feature and ore feature found at https://github.com/bridge-core/bridge./blob/master/static/file_creator/feature.json have had an update in their schemas for 1.17. Additionally, a slew of new feature types have been added, tripling the old count. It’s challenging to recommend a “default” for some of these features, but I have code for every type if needed.

**Comment by solvedDev** [comment]
@Joelant05 Can we look into updating the file creator templates & vanilla files for v1.8?

**Comment by Joelant05** [comment]
Yep, we can definitely get this into v1.8 👍
