### ISSUE TITLE
[BUG] Saving blocks.json overwrites sounds.json within bridge.

### ISSUE THREAD

**Issue by Chikorita-Lover** [bridge-core/bridge.#365]
**Summary**
When saving the `blocks.json` file in the resource pack, the file saves as expected. However, its content are copied over to `sounds.json` within bridge., completely overwriting the file. The contents of `sounds.json` are not affected, but appear to have the same contents as `blocks.json` within bridge. Refreshing bridge.'s cache does not resolve the issue.

**To Reproduce**
1. Open `blocks.json`
2. Edit and save the file
3. Open `sounds.json` within bridge.
4. Observe result

**Observed behavior**
The contents of `blocks.json` completely replace the contents of `sounds.json` within bridge. when the former file is saved. `sounds.json` is not truly affected.
**Expected behavior**
The `sounds.json` file should appear as itself when viewed within bridge., and not be affected by `blocks.json`.

**Platform:**
 - OS: Windows 10
 - App Version: 1.7.18

**Comment by solvedDev** [comment]
That's a strange one... 🤔

**Comment by Chikorita-Lover** [comment]
**Update**: The `sounds.json` file isn't actually affected, and it seems to be some sort of cache issue. However, refreshing the project's cache does not resolve the issue.

**Comment by solvedDev** [comment]
Refreshing the project cache only refreshes the lightning cache. I am closing this issue because we don't plan on fixing cache issues
