### ISSUE TITLE
[BUG] 'Add Object' menu does not populate with appropriate items

### ISSUE THREAD

**Issue by jglazman** [bridge-core/bridge.#406]
**Summary**
I just discovered 'bridge.' (btw, it's very difficult to search for 'minecraft bridge' and get relevant results, for obvious reasons) and quickly noticed that the 'Add Object' menu does not work as expected compared to any of the videos I've watched on Youtube.  Specifically, the appropriate items do not appear in the list as they do in all of the videos.

**To Reproduce**
1. Create a new project with 'Behavior' and 'Resource' packs enabled.
2. Click on 'File -> New File -> Item -> Blank Item'.  Notice that the interface has completely changed compare to youtube videos from early 2021; most notably the templates no longer exist, instead the only option is 'blank item'.
3. Notice that the item defaults to "format_version":"1.10.0", which is very old (January 2019).
3. Click on 'components' in the item json file, then click on 'Add Object'.  Notice that only a few items are in the list.
4. Right-click on 'components' and select 'View documentation'.  Notice that 1.18.1.2 (Stable) is the default version in the documentation, and that almost none of the components in the documentation appear in the 'components' list in bridge..
5. Change "format_version" to "1.18.1.2", "1.18.0", "1.17.0", etc., then click click on 'components' and then 'Add Object'.  Notice that now the list is completely empty.

**Expected behavior**
This seems to be a regression bug compared to these earlier bridge. videos, where the 'Add Objects' list has many more options:
* https://www.youtube.com/watch?v=zfGdlZQZZTM&ab_channel=Spyderrock
* https://www.youtube.com/watch?v=CJAR23LgxWo&ab_channel=DanRobzProbz

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 96.0.4664.110

**Comment by solvedDev** [comment]
You need to change the format version in order to get more options inside of the auto-completion field. That's just how bridge. works (v1 and v2) because it helps people to specifically target a Minecraft version to develop for. That is e.g. important for Marketplace partners because they're only allowed to use the v1.10.0 item syntax (no experimental gameplay allowed)
