### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cccwro** [bridge-core/bridge.#452]
**Summary**
 I am using Minecraft Education Edition 1.20.12 and creating a custom sword on 'Bridge.' . It has its correct texture and durability but it won't deal its normal damage to mobs and can't break bamboo and cobwebs properly. Please Help!!!!!!!!!!!!! (By the way, I can't use Discord yet so maybe someone who can use Discord could bring it up on the Bridge. discord server and send the answer here. ) Thank you in Advance.

**To Reproduce**
1. Copy the code in the "Additional Context" section
2. Create a new Bridge. project with the project prefix being 'stat'
3. Create a blank item called 'venom_excalibur' with its display name being 'Venom Excalibur'
4. Paste the code inside items/venom_excalibur.json
5. Import this photo into Bridge and name it 'venom_excalibur.png'
![sting_sword-1 png](https://github.com/bridge-core/bridge./assets/129770037/f364f8ed-39b3-4964-a9f4-86ee00b83a33)
6. Delete the default texture
7. Make sure that in item_texture.json looks like this: `{
	"resource_pack_name": "<YOUR_RESOURCE_PACK_NAME>",
	"texture_name": "atlas.items",
	"texture_data": {
		"stat_venom_excalibur": {
			"textures": "textures/items/venom_excalibur"
		}
	}
}`
8.  Create a new world with cheats and creative mode on  
9. Start testing what I've said. You'll soon see it's true.

**Observed behaviour**
It has its correct texture and durability but it won't deal its normal damage to mobs and can't break bamboo and cobwebs properly. 
**Expected behaviour**
It should have its correct texture, durability, amount of damage dealt and should break cobwebs and bamboo correctly.
**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform **
 - OS: Windows 10
 - App Version: Minecraft Education Edition1.20.12

**Additional context**
Here is the code:
`{
	"format_version": "1.20.10",
	"minecraft:item": {
		"description": {
			"identifier": "stat:venom_excalibur"
		},
		"components": {
			"minecraft:icon": {
				"texture": "stat_venom_excalibur"
			},
			"minecraft:max_stack_size": 1,
			"minecraft:creative_category": {
				"category": "equipment",
				"group": "itemGroup.name.sword"
			},
			"minecraft:display_name": {
				"value": "Venom Excalibur"
			},
			"minecraft:hand_equipped": true,
			"minecraft:weapon": {
				"on_hit_block": {
					"event": "dmg"
				},
				"on_hurt_entity": {
					"event": "dmg"
				},
				"on_not_hurt_entity": {
					"event": "dmg"
				}
			},
			"minecraft:damage": 9,
			"minecraft:can_destroy_in_creative": false,
			"minecraft:durability": {
				"max_durability": 4000
			},
			"minecraft:mining_speed": 1.5,
			"minecraft:enchantable": {
				"slot": "sword",
				"value": 50
			},
			"minecraft:digger": {
				"use_efficiency": false,
				"on_dig": {
					"event": "dmg"
				},
				"destroy_speeds": [
					{
						"block": "minecraft:web",
						"speed": 15,
						"on_dig": {
							"event": "dmg"
						}
					},
					{
						"block": "minecraft:bamboo",
						"speed": 60,
						"on_dig": {
							"event": "dmg"
						}
					}
				]
			}
		},
		"events": {
			"dmg": {
				"damage": {
					"type": "none",
					"amount": 1,
					"target": "self"
				}
			}
		}
	}
}`

```[tasklist]
### Tasks
```

**Comment by outercloudstudio** [comment]
This GitHub is for issues with the bridge program itself. If you have problems with addons, you can join our discord server and ask for help there.
