### ISSUE TITLE
[BUG] 2.6.3 - Web-app and Downloaded App

### ISSUE THREAD

**Issue by dacowan** [bridge-core/bridge.#453]
**Summary**
With Microsoft Edge as the primary browser (117.0.2045.60 Official Build x64) - the lower pane of the JSON editor (the one with the Add combo box for editing JSON properties) does not appear.

If I set Google Chrome to the primary browser (or navigate to bridge-core.app using Chrome), the pane is visible and working.

**Platform (please complete the following information):**
 - OS: Windows 11 (latest build)
 - App Version: 2.6.3

**Comment by outercloudstudio** [comment]
Can you please attach a screenshot?

**Comment by dacowan** [comment]
My bad.  I got it working eventually -- I had to recreate the project and ensure tree editing was enabled and did a lot of other fiddling, and eventually it started displaying.
Sorry for the terrible bug report quality, but I have no idea what caused it or how I resolved it other than acting as a chaos agent :)
