### ISSUE TITLE
[BUG] Installer is detected as a threat

### ISSUE THREAD

**Issue by Aroulis8** [bridge-core/bridge.#455]
I am trying to download the .msi installer and my system dedects it as a threat

 - OS: Windows 10

**Comment by outercloudstudio** [comment]
Thank you for reporting! This seems to be a response to windows defender since we haven't signed the program due to it costing money I believe. I assure you that it is safe to run anyway. If you still have qualms, feel free to use the web version available at https://editor.bridge-core.app

**Comment by Aroulis8** [comment]
Ok

**Comment by Aroulis8** [comment]
Thank you
