### ISSUE TITLE
[Feature] Tool item template sets

### ISSUE THREAD

**Issue by EndiKM** [bridge-core/bridge.#67]
The Tools tab would help create better tools. I wanted to suggest it a long time ago :D.

**Comment by solvedDev** [comment]
"Tools"? Do you mean weapons, pickaxes etc.?

**Comment by EndiKM** [comment]
Yes

**Comment by solvedDev** [comment]
Okay, currently custom tools are not supported by Minecraft yet. However, once they are, I plan on adding new template sets for the new item types. This basically allows you to create a set of files through a clear UI
